version: '3.8'

services:
  gotextsearch:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
      - gotextsearch-data:/data
    environment:
      - GOTEXTSEARCH_LOG_LEVEL=debug
      - GOTEXTSEARCH_DATA_DIR=/data

volumes:
  go-modules:
  gotextsearch-data:
